name: Content Build (main)

on:
  push:
    branches: [ main ]
    paths-ignore:
      - rmotw/**
      - .github/**

jobs:
  build:
    runs-on: ubuntu-latest
    #if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install requirements
        run: sudo npm install -g sass && pip install -r requirements.txt
      - name: Build documents
        run: make html
      - name: Compress output
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r main-output.zip output
      - uses: actions/upload-artifact@v2
        with:
          name: main-output
          path: main-output.zip
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: main-output
      - name: Public release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: published
          prerelease: false
          draft: false
          files: main-output.zip
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/download-artifact@v2
        with:
          name: main-output
      - uses: montudor/action-zip@v1
        with:
          args: unzip -qq main-output.zip -d output
      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: output
          clean: true
          clean-exclude: |
            CNAME
            .nojekyll